image: node:10-alpine

stages:
  - test
  - quality
  - deploy

variables:
  SONAR_URL: 'http://sonarqube.services.url:port'
  SONAR_LOGIN: '--your sonar login--'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

lint:
  stage: test
  script:
  - npm ci
  - npm run lint

unit_tests:
  stage: test
  script:
  - npm ci
  - npm run test:ci
  artifacts:
    paths:
      - coverage
    expire_in: 1 day



publish:
  stage: deploy
  script:
    - npm ci
    - npm run dist
    - npm publish
  only:
    - tags
    - triggers


sonar-quality-gate:
  image: gitlab-ci-sonarqube-image
  stage: quality
  script:
    - sonar-scanner -Dsonar.projectVersion=${CI_COMMIT_SHA}
  allow_failure: true


sonar-comments:
  image: gitlab-ci-sonarqube-image
  stage: quality
  except:
    - master
  script:
    - sonar-scanner-preview -Dsonar.projectVersion=${CI_COMMIT_SHA}
  allow_failure: true
