severity: error

files:
  include:
    - 'src/**/*.s+(a|c)ss'
  ignore:
    - 'node_modules/**/*.s+(a|c)ss'
    - 'test/**/*.s+(a|c)ss'

rules:
  indentation:
    - 2
    -
      size: 4

  class-name-format:
    - 1
    - convention: '([a-z0-9_]+-?)+'

  mixin-name-format:
    - 1
    - convention: '([a-z0-9_]+-?)+'
  
  placeholder-name-format:
    - 1
    - convention: '([a-z0-9_]+-?)+'

  variable-name-format:
    - 1
    - convention: '([a-z0-9]+-?)+'

  space-before-brace:
    - 2
  
  no-important:
    - 2

linters:

  BorderZero:
    enabled: true
    convention: zero

  BemDepth:
    enabled: true

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: true

  PrivateNamingConvention:
    enabled: true
    prefix: _

  PropertySortOrder:
    enabled: false

  QualifyingElement:
    enabled: false

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
    class_convention: ^(?!js-).*
    class_convention_explanation: should not be written in the form js-*

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  StringQuotes:
    enabled: true
    style: double_quotes
